#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 1a30e612-0f55-4e38-8f7a-821390e2e129
# Source File: ..\Documents\SAPIEN\PowerShell Studio\Files\ExpandCanvasCourse.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
kysAAB+LCAAAAAAABADdWm1v4kYQ/l6p/2Fr9UNbIcCAz1ABUoBwFzVpEM7d9UOlaLHX4LJ40XpJ
oOqP76zXJAQn5zUJFjlFiiDZ2Xl25vG8rdtj4rI7wjcDLDCCD1HAwo5RK5tG98cfEGpf82AahJgO
A0r+xAvSPV8vcej1cXiHoz5b8YiUl5HfrqQWKvHJP8QVSGyWpGM4m0iQRflrEHrsPioPGV+o3yX0
3L9K6EuCp1Guyp8S6q+oWHHSCclKcExLaLSa0MD9g2xu2JyEnYltY8u1PpiteoNUmy0DhQClY/iw
n2kgdxZQj8M6o89CwRmN1CkB6IizJeFikwicrQRzXEzJIFiQUIKApR9KyKy3K9ulWaJXzCNGdwia
MmX6NCChcIJ/QaDeMEsIfmUKSSP1GPcId8SGSlXBmniDAFM2zRSWLjK6sV0y196QtZAH4Yv00vM7
AJ6su2TYS/a8lZ/blfi/26XZXOjPiDvvsfXR+eBKRRO2Hg2G1yHdfIsZaXOch3hCCZx0iGlEUiZJ
C1wyFwvAbXRrdQBtNmsaQspBe0A15BSJzGqjhGoNjfU3eHIRemQNMmkmvMQFgIM08XyOSJ8tlmAA
MJqUHhNQx4NwanRv+ErHfrDFlyBaYRrzvIfdeZ9Rxl+Qh1AUE02fdr2VECw8OukmsZqPLB/bZPww
uleBy1nEfIEcHEbIAQP6JdQs16ylKKFI2qXTY9TLx0YLIlqtZmuzcXsCbRraFihIh8xvsrCqzcKP
7KdTJOBeVITY7s4fbXcbf98Ljbkpe4knhB6dsVRqGZBIQGKXlBkCwwgfYZGPwnFGjPmgae9Hipo1
iJemThxTDH0RsX7kNG1QqfNMPHK2pU3ZHWjIj7EhYObsGDQ+aVI5UDm6JFhErisLxkL5ZOm4a4dO
e1i1mdSq5yZSU5tIChQqx7CQr4erAA4Vmkt7HPYmt97jQ5WPSDupsBUX9/qF2UsAtNkhK8GcqVGr
nIvZUS6X31tmTJtSZcr6a1OlPFgRPYUAPVCpH85GGdakPygRSe/orKZT2O1suQTHaHhjdwcVIGRT
SIk6+SDgYCrGAxLlz8F1/Rz8jCG0n4qa3YTHQqsEfHgsnmnJTztsjYnPSTQ7NFbJvJK/ak+UanvC
auSOT1q5Lo5P+mBOKkYlsN+mhC86LjkCi1V0KOlkEIB+UcPcV4AzoEGoX549DRsKp4bYmGAvnt7o
6nGgh6a0hzmcGMwrAhdT/XxttkrIzvdApM2VnyaFz8SAFXeA+IaNBsOCB2OWlXswtos2x3RMjljz
ZRkdaCq4JZCQYEgP1DsYkRXYGqYvGI7cHX5rwmZaZdta6kwPHrlsWSWUs8VMn1m/YqpbubmsFcVi
LitgSCFD2tC+t0bzNlLV9Gu6SztvxZYoPWZHqT/xf4cdZWI/Va3V3lu5dgjjjt1B5m4bbf04+PTc
R20Y06tPnw7385lYUMGWnv/KQl72dTWdQeNTv6QAHKVCV7dGdm6X6gzupMvOaDAFI/QhEhD+vuqi
r69jwGuG5pIyVX3KPA9Xf27ezD03189jOzRGkS6u762cGbD7kMqXNYpq78xG65CZ1RbnMe+b9a+b
c6A5qTpoiztzbPX0SzZnr6GokMWBeuXo6NyFA4fyosuL1d1uy5PkIHvmGxAfg55z6Tixzn4DC84B
GQEyw26ng35R92u//veb+pC5zUUYCIC3HbVD5vuZhHe/f3bOx6Px9fDi8vzvAYnmEH8yt3Jm7P4T
octnPZ7XVeoeXN2x8IL8pe63J0pn4rTB7uVIRaE/iyKygB1JtLVE8pdNF2zOOA0mb4CqXXnYdV+L
skMROt7c1tka5YudxSji+B4C3CG6qnXf8m3fND2rius4W9dfC1rImfqMk7dX9PBVUb5d2X0Jt/s/
gp0Gs5MrAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.145
     Generated on:       3/21/2018 7:31 AM
     Generated by:       Administrator
     Organization:       InterMountain ESD
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2017
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-ExpandCanvasCourse_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$checkboxPDFOnly = New-Object 'System.Windows.Forms.CheckBox'
	$buttonGo = New-Object 'System.Windows.Forms.Button'
	$labelDestinationFolderPat = New-Object 'System.Windows.Forms.Label'
	$labelSourceimsccFile = New-Object 'System.Windows.Forms.Label'
	$buttonBrowse_destination = New-Object 'System.Windows.Forms.Button'
	$textbox_destination = New-Object 'System.Windows.Forms.TextBox'
	$buttonRefresh = New-Object 'System.Windows.Forms.Button'
	$textbox_Status = New-Object 'System.Windows.Forms.TextBox'
	$checkboxConvertToPDF = New-Object 'System.Windows.Forms.CheckBox'
	$labelExpandCanvasCourse = New-Object 'System.Windows.Forms.Label'
	$button_source = New-Object 'System.Windows.Forms.Button'
	$textbox_source = New-Object 'System.Windows.Forms.TextBox'
	$textbox_wkhtmltopdfStatus = New-Object 'System.Windows.Forms.TextBox'
	$labelWkhtmltopdfStatus = New-Object 'System.Windows.Forms.Label'
	$buttonDownload = New-Object 'System.Windows.Forms.Button'
	$openfiledialog_Source = New-Object 'System.Windows.Forms.OpenFileDialog'
	$folderbrowserdialog_Destination = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load = {
		$global:Architecture = (Get-CimInstance Win32_OperatingSystem).OSArchitecture
		$global:PDFConverterStatus = Get-wkhtmltopdfStatus
		[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
	}
	
	function Get-wkhtmltopdfStatus
	{
		$global:Check32 = Test-Path -Path 'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe'
		$global:Check64 = Test-Path -Path 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
		[bool]$wkhtmltopdfstatus = $false
		
		if ($Check32 -eq $true -or $Check64 -eq $true)
		{
			$textbox_wkhtmltopdfStatus.BackColor = 'Green'
			$textbox_wkhtmltopdfStatus.Text = "Installed"
			$wkhtmltopdfstatus = $true
			$buttonDownload.Enabled = $false
			$checkboxConvertToPDF.Enabled = $true
			$checkboxPDFOnly.Enabled = $true
		}
		if ($Check32 -eq $false -and $Check64 -eq $false)
		{
			$textbox_wkhtmltopdfStatus.BackColor = 'Red'
			$textbox_wkhtmltopdfStatus.Text = "Missing"
			$buttonDownload.Enabled = $true
		}
		$wkhtmltopdfstatus
	}
	
	function Expand-CanvasCourse
	{
		$textbox_Status.Text += "Preparing imscc for extraction...`r`n"
		$NewArchiveName = $IMSCC.replace('.imscc', '.zip')
		Rename-Item -Path $IMSCC -NewName $NewArchiveName -Force
		$textbox_Status.Text += "Expanding imscc...`r`n"
		Expand-Archive -Path $NewArchiveName -DestinationPath $OutPath -Force
		$textbox_Status.Text += "Finished expanding archive!`r`n"
		Rename-Item -Path $NewArchiveName -NewName $IMSCC -Force
		
		$textbox_Status.Text += "Repairing HTML content...`r`n"
		$htmlObjects = Get-ChildItem -Path $OutPath -Recurse -Include "*.html"
		foreach ($htmlObject in $htmlObjects)
		{
			(Get-Content $htmlObject).Replace('%24IMS-CC-FILEBASE%24', '../web_resources') | Set-Content $htmlObject -Force
			(Get-Content $htmlObject).Replace('%20', ' ') | Set-Content $htmlObject -Force
		}
		
		$textbox_Status.Text += "HTML content repaired!`r`n"
		if ($checkboxConvertToPDF.Checked -eq $false) { $textbox_Status.Text += "Finished!`r`nContent located at $OutPath`r`n"; }
		
		if ($checkboxConvertToPDF.Checked -eq $true)
		{
			$textbox_Status.Text += "Converting documents to PDF...`r`n"
			foreach ($htmlObject in $htmlObjects)
			{
				$TempName = $htmlObject.Name
				$TempName = $TempName.Replace(".html", ".pdf")
				$TempName = "$OutPath\$TempName"
				if ($Architecture -eq "32-bit") { & 'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe' -q $htmlObject $TempName}
				if ($Architecture -eq "64-bit") { & 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe' -q $htmlObject $TempName}
			}
			New-Item -ItemType Directory -Path $OutPath\PDF
			Get-ChildItem -Path $OutPath\* -Include "*.pdf" | Move-Item -Destination "$OutPath\PDF"
		}
		if ($checkboxPDFOnly.Checked -eq $true) { Get-ChildItem -Path $OutPath -Exclude "*.pdf" | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue }
		$textbox_Status.Text += "Finished!`r`nContent located at $OutPath`r`n"
	}
	
	$button_source_Click2={
	
		if($openfiledialog_Source.ShowDialog() -eq 'OK')
		{
			$textbox_source.Text = $openfiledialog_Source.FileName
		}
	}
	
	$buttonRefresh_Click={
		$global:PDFConverterStatus = Get-wkhtmltopdfStatus
	}
	
	$buttonBrowseFolder_Click2={
		if($folderbrowserdialog_Destination.ShowDialog() -eq 'OK')
		{
			$textbox_destination.Text = $folderbrowserdialog_Destination.SelectedPath
		}
	}
	
	$buttonBrowse_destination_Click3={
		if($folderbrowserdialog_Destination.ShowDialog() -eq 'OK')
		{
			$textbox_destination.Text = $folderbrowserdialog_Destination.SelectedPath
		}
	}
	
	$buttonDownload_Click={
		if ($Architecture -eq "32-bit")
		{
			$textbox_Status.Text += "Detected 32 bit Operating System...`r`n"
			$textbox_Status.Text += "Downloading 32 bit wkhtmltopdf to $env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win32.exe`r`n"
			if ((Test-Path "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win32.exe") -eq $true){ Remove-Item "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win32.exe" -Force}
			iwr -Uri "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_mingw-w64-cross-win32.exe" -OutFile "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win32.exe"
			$textbox_Status.Text += "Downloaded. Launching installer...`r`n"
			& "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win32.exe"
		}
		if ($Architecture -eq "64-bit")
		{
			$textbox_Status.Text += "Detected 64 bit Operating System...`r`n"
			$textbox_Status.Text += "Downloading 64 bit wkhtmltopdf to $env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win64.exe`r`n"
			if ((Test-Path "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win64.exe") -eq $true) { Remove-Item "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win64.exe" -Force }
			iwr -Uri "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_mingw-w64-cross-win64.exe" -OutFile "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win64.exe"
			$textbox_Status.Text += "Downloaded. Launching installer...`r`n"
			& "$env:TEMP\wkhtmltox-0.12.4_mingw-w64-cross-win64.exe"
		}
	}
	
	$buttonGo_Click={
		$global:IMSCC = $textbox_source.Text
		$global:OutPath = $textbox_destination.Text
		if ($IMSCC -eq $null -or $IMSCC -eq "") { $textbox_Status.Text += "Please select an .imscc file!`r`n"; break }
		if ($OutPath -eq $null -or $OutPath -eq "") { $textbox_Status.Text += "Please select a destination directory!`r`n"; break }
		if ($IMSCC -ne $null -and $IMSCC -ne "" -and $OutPath -ne $null -and $OutPath -ne "")
		{
			Expand-CanvasCourse
		}
	}
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonGo.remove_Click($buttonGo_Click)
			$buttonBrowse_destination.remove_Click($buttonBrowse_destination_Click3)
			$buttonRefresh.remove_Click($buttonRefresh_Click)
			$button_source.remove_Click($button_source_Click2)
			$buttonDownload.remove_Click($buttonDownload_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($checkboxPDFOnly)
	$form1.Controls.Add($buttonGo)
	$form1.Controls.Add($labelDestinationFolderPat)
	$form1.Controls.Add($labelSourceimsccFile)
	$form1.Controls.Add($buttonBrowse_destination)
	$form1.Controls.Add($textbox_destination)
	$form1.Controls.Add($buttonRefresh)
	$form1.Controls.Add($textbox_Status)
	$form1.Controls.Add($checkboxConvertToPDF)
	$form1.Controls.Add($labelExpandCanvasCourse)
	$form1.Controls.Add($button_source)
	$form1.Controls.Add($textbox_source)
	$form1.Controls.Add($textbox_wkhtmltopdfStatus)
	$form1.Controls.Add($labelWkhtmltopdfStatus)
	$form1.Controls.Add($buttonDownload)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '341, 341'
	$form1.FormBorderStyle = 'FixedDialog'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# checkboxPDFOnly
	#
	$checkboxPDFOnly.Enabled = $False
	$checkboxPDFOnly.Location = '230, 182'
	$checkboxPDFOnly.Name = 'checkboxPDFOnly'
	$checkboxPDFOnly.Size = '104, 24'
	$checkboxPDFOnly.TabIndex = 11
	$checkboxPDFOnly.Text = 'PDF Only'
	$checkboxPDFOnly.UseCompatibleTextRendering = $True
	$checkboxPDFOnly.UseVisualStyleBackColor = $True
	#
	# buttonGo
	#
	$buttonGo.Font = 'Microsoft Sans Serif, 8.25pt, style=Bold'
	$buttonGo.Location = '256, 227'
	$buttonGo.Name = 'buttonGo'
	$buttonGo.Size = '75, 23'
	$buttonGo.TabIndex = 10
	$buttonGo.Text = 'Go!'
	$buttonGo.UseCompatibleTextRendering = $True
	$buttonGo.UseVisualStyleBackColor = $True
	$buttonGo.add_Click($buttonGo_Click)
	#
	# labelDestinationFolderPat
	#
	$labelDestinationFolderPat.AutoSize = $True
	$labelDestinationFolderPat.Location = '12, 114'
	$labelDestinationFolderPat.Name = 'labelDestinationFolderPat'
	$labelDestinationFolderPat.Size = '117, 17'
	$labelDestinationFolderPat.TabIndex = 9
	$labelDestinationFolderPat.Text = 'Destination folder path'
	$labelDestinationFolderPat.UseCompatibleTextRendering = $True
	#
	# labelSourceimsccFile
	#
	$labelSourceimsccFile.AutoSize = $True
	$labelSourceimsccFile.Location = '12, 59'
	$labelSourceimsccFile.Name = 'labelSourceimsccFile'
	$labelSourceimsccFile.Size = '93, 17'
	$labelSourceimsccFile.TabIndex = 8
	$labelSourceimsccFile.Text = 'Source .imscc file'
	$labelSourceimsccFile.UseCompatibleTextRendering = $True
	#
	# buttonBrowse_destination
	#
	$buttonBrowse_destination.Location = '296, 132'
	$buttonBrowse_destination.Name = 'buttonBrowse_destination'
	$buttonBrowse_destination.Size = '30, 23'
	$buttonBrowse_destination.TabIndex = 4
	$buttonBrowse_destination.Text = '...'
	$buttonBrowse_destination.UseCompatibleTextRendering = $True
	$buttonBrowse_destination.UseVisualStyleBackColor = $True
	$buttonBrowse_destination.add_Click($buttonBrowse_destination_Click3)
	#
	# textbox_destination
	#
	$textbox_destination.AutoCompleteMode = 'SuggestAppend'
	$textbox_destination.AutoCompleteSource = 'FileSystemDirectories'
	$textbox_destination.Location = '12, 134'
	$textbox_destination.Name = 'textbox_destination'
	$textbox_destination.Size = '278, 20'
	$textbox_destination.TabIndex = 3
	#
	# buttonRefresh
	#
	$buttonRefresh.Location = '93, 227'
	$buttonRefresh.Name = 'buttonRefresh'
	$buttonRefresh.Size = '54, 23'
	$buttonRefresh.TabIndex = 7
	$buttonRefresh.Text = 'Refresh'
	$buttonRefresh.UseCompatibleTextRendering = $True
	$buttonRefresh.UseVisualStyleBackColor = $True
	$buttonRefresh.add_Click($buttonRefresh_Click)
	#
	# textbox_Status
	#
	$textbox_Status.Location = '12, 256'
	$textbox_Status.Multiline = $True
	$textbox_Status.Name = 'textbox_Status'
	$textbox_Status.ReadOnly = $True
	$textbox_Status.ScrollBars = 'Vertical'
	$textbox_Status.Size = '319, 73'
	$textbox_Status.TabIndex = 6
	#
	# checkboxConvertToPDF
	#
	$checkboxConvertToPDF.Enabled = $False
	$checkboxConvertToPDF.Location = '230, 155'
	$checkboxConvertToPDF.Name = 'checkboxConvertToPDF'
	$checkboxConvertToPDF.Size = '101, 30'
	$checkboxConvertToPDF.TabIndex = 5
	$checkboxConvertToPDF.Text = 'Convert to PDF'
	$checkboxConvertToPDF.UseCompatibleTextRendering = $True
	$checkboxConvertToPDF.UseVisualStyleBackColor = $True
	#
	# labelExpandCanvasCourse
	#
	$labelExpandCanvasCourse.AutoSize = $True
	$labelExpandCanvasCourse.Font = 'Microsoft Sans Serif, 15.75pt'
	$labelExpandCanvasCourse.Location = '55, 9'
	$labelExpandCanvasCourse.Name = 'labelExpandCanvasCourse'
	$labelExpandCanvasCourse.Size = '235, 30'
	$labelExpandCanvasCourse.TabIndex = 3
	$labelExpandCanvasCourse.Text = 'Expand Canvas Course'
	$labelExpandCanvasCourse.UseCompatibleTextRendering = $True
	#
	# button_source
	#
	$button_source.Location = '296, 77'
	$button_source.Name = 'button_source'
	$button_source.Size = '30, 23'
	$button_source.TabIndex = 1
	$button_source.Text = '...'
	$button_source.UseCompatibleTextRendering = $True
	$button_source.UseVisualStyleBackColor = $True
	$button_source.add_Click($button_source_Click2)
	#
	# textbox_source
	#
	$textbox_source.AutoCompleteMode = 'SuggestAppend'
	$textbox_source.AutoCompleteSource = 'FileSystem'
	$textbox_source.Location = '12, 79'
	$textbox_source.Name = 'textbox_source'
	$textbox_source.Size = '278, 20'
	$textbox_source.TabIndex = 0
	#
	# textbox_wkhtmltopdfStatus
	#
	$textbox_wkhtmltopdfStatus.Location = '14, 228'
	$textbox_wkhtmltopdfStatus.Name = 'textbox_wkhtmltopdfStatus'
	$textbox_wkhtmltopdfStatus.ReadOnly = $True
	$textbox_wkhtmltopdfStatus.Size = '77, 20'
	$textbox_wkhtmltopdfStatus.TabIndex = 2
	$textbox_wkhtmltopdfStatus.TextAlign = 'Center'
	#
	# labelWkhtmltopdfStatus
	#
	$labelWkhtmltopdfStatus.AutoSize = $True
	$labelWkhtmltopdfStatus.Location = '14, 208'
	$labelWkhtmltopdfStatus.Name = 'labelWkhtmltopdfStatus'
	$labelWkhtmltopdfStatus.Size = '98, 17'
	$labelWkhtmltopdfStatus.TabIndex = 1
	$labelWkhtmltopdfStatus.Text = 'wkhtmltopdf status'
	$labelWkhtmltopdfStatus.UseCompatibleTextRendering = $True
	#
	# buttonDownload
	#
	$buttonDownload.Enabled = $False
	$buttonDownload.Location = '149, 227'
	$buttonDownload.Name = 'buttonDownload'
	$buttonDownload.Size = '75, 23'
	$buttonDownload.TabIndex = 0
	$buttonDownload.Text = 'Download'
	$buttonDownload.UseCompatibleTextRendering = $True
	$buttonDownload.UseVisualStyleBackColor = $True
	$buttonDownload.add_Click($buttonDownload_Click)
	#
	# openfiledialog_Source
	#
	$openfiledialog_Source.DefaultExt = 'txt'
	$openfiledialog_Source.Filter = 'Canvas Course (.imscc)|*.imscc'
	$openfiledialog_Source.InitialDirectory = "$env:USERPROFILE\Desktop"
	$openfiledialog_Source.ShowHelp = $True
	#
	# folderbrowserdialog_Destination
	#
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-ExpandCanvasCourse_psf | Out-Null
